### ISSUE TITLE
feat: supports new user flags

### ISSUE THREAD

**Issue by pnr-8** [FnrDev/slash-commands#82]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]
- In discord.js v14 they changed user flags name, in order to support that you need to change user flags in `/badges` command

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Change badges choises value in badges command

**Comment by Wumpus2000** [comment]
bro i am keep getting this




PS C:\Users\usery\Desktop\mod-bot> node index.js
C:\Users\usery\Desktop\mod-bot\node_modules\discord.js\src\structures\ActionRow.js:6
class ActionRow extends BuildersActionRow {
                        ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\usery\Desktop\mod-bot\node_modules\discord.js\src\structures\ActionRow.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\usery\Desktop\mod-bot\node_modules\discord.js\src\index.js:73:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by FnrDev** [comment]
@Wumpus2000 is not related to this issue, please check the guide before!
