### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Guillaume0001** [FnrDev/slash-commands#99]
Hello, I have this error when I launch the bot:

TypeError: discord_js_1.Intents is not a constructor
    at /home/runner/slash-commands/node_modules/discord-logs/lib/index.js:47:19
    at step (/home/runner/slash-commands/node_modules/discord-logs/lib/index.js:33:23)
    at Object.next (/home/runner/slash-commands/node_modules/discord-logs/lib/index.js:14:53)
    at /home/runner/slash-commands/node_modules/discord-logs/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/slash-commands/node_modules/discord-logs/lib/index.js:4:12)
    at module.exports (/home/runner/slash-commands/node_modules/discord-logs/lib/index.js:41:54)
    at Object.<anonymous> (/home/runner/slash-commands/index.js:11:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/home/runner/slash-commands/node_modules/discord.js/src/client/Client.js:214:52)
    at Object.<anonymous> (/home/runner/slash-commands/index.js:26:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 4
}

Do you now what is the problem ?

**Comment by FnrDev** [comment]
it's because we are updating discord.js to version 14, and there are some lib's doesn't support version 14 yet!
